### ISSUE TITLE
The source directory   /windows/flutter/ephemeral/.plugin_symlinks/window_utils/windows    does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by Ztagdev** [adrianjagielak/window_utils#1]
Working on flutter desktop application and want to remove titlebar of windows. When I try to run code it gives this compilation error. I tried all version and now using the lowest one but still same.
This is the error what i got.

CMake Error at flutter/generated_plugins.cmake:13 (add_subdirectory):
  The source directory

    D:/FoodOrderApp/plugin_test/windows/flutter/ephemeral/.plugin_symlinks/window_utils/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)

Building Windows application...
Exception: Unable to generate build files

**Comment by adrianjagielak** [comment]
The window_utils is now considered legacy, check out the new official [Flutter Desktop Plugins](https://github.com/google/flutter-desktop-embedding/tree/master/plugins) and add it to your pubspec.yaml like this:

```
dependencies:
  ...
  menubar:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3
```
